audio-helper: include openxtalsa.h
We have some implicit declaration warnings:

| ../../git/audio_helper/src/main.c: In function 'parse_options':
| ../../git/audio_helper/src/main.c:76:23: warning: implicit declaration of function 'openxt_alsa_set_card' [-Wimplicit-function-declaration]
|                  ret = openxt_alsa_set_card(snd_card_get_index(optarg));
|                        ^~~~~~~~~~~~~~~~~~~~

Include openxtalsa.h where openxt_alsa_set_card is defined.

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>