xcpmd: Fix -Werror=format-security errors
We have assorted errors of the form:
| ../../git/xcpmd/src/battery.c:742:29: error: format not a string literal and no format arguments [-Werror=format-security]
|          xenstore_write("0", xenstore_path);
|                              ^~~~~~~~~~~~~

They are mostly preceded by an snprintf, so we can just fold the format
string into the xenstore_ call.

OXT-1697

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>